FROM golang:1.21 AS builder
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
WORKDIR /app
COPY main.go .
RUN go build -o app main.go
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/app .
CMD ["./app"]
