FROM ubuntu:22.04
LABEL maintainer="uday2"
LABEL description="Clean and optimized Flask Dockerfile"
WORKDIR /app
RUN apt-get update && \
    apt-get install -y python3 python3-pip curl git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python3", "app.py"]
